version: '3.6'
services:
  web:
    environment:
      - DATABASE_URL=mysql://db:db@db/db
      - WP_CORE=/var/www/html/web/wp
      - WP_HOME=http://urbantechhelsinki.ddev.site
        # - DOMAIN_CURRENT_SITE=urbantechhelsinki.ddev.site
